name: Docker Image mssql-tools CI

on:
  push:
    branches: [ "develop", "features/fase3/mssql-tools" ]
  pull_request:
    branches: [ "develop", "features/fase3/mssql-tools" ]

jobs:

  build:

    name: Build mssql-tools docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
        
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}
    
    - name: Build and Push to DockerHub
      # You may pin to the exact commit or the version.
      # uses: MaximilianoBz/dockerhub-buildpush@372110d600041736063b948d05005b6039d8fb0c
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        # Docker Registry Url, eg: docker.io
        registry_url: 'docker.io'
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: fiap-pos-techchallenge-gurpo-71-scripts-database
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: ${{ secrets.DOCKER_USERNAME }}
        # Docker Login Access Token, from: https://hub.docker.com/
        password: ${{ secrets.DOCKER_TOKEN }}
        # Image Build Version
        image_version: 'fase3'
        # Docker File Directory, Default Current Directory (.)
        docker_file: './Src/Docker'

    - name: Get pre step result output image_pull_url
      run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
          
